server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:}
    password: ${DBMS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
          debug: true

gemini:
  api:
    key: ""

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

app:
  file:
    upload-dir: uploads
    base-url: http://localhost:8080/identity