server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:}
    password: ${DBMS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "qgHgeQJRSyq51d7huno8e/gIifKTtvKw8dcUAt3fOVh54QHaoEaZ5CvlAI2ghPCe"
  valid-duration: 7200 # in second
  refreshable-duration: 72000 # in seconds
